### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by britov** [danilocoppi/flutter-textfield-mask#10]
Lets migrate to null safety

**Comment by hiuryanderson** [comment]
Great idea

**Comment by lucas-gauer** [comment]
I already made a pull request. Would appreciate some feedback on it

**Comment by anisalibegic** [comment]
@danilocoppi Did you forgot to release an update on pub.dev after merging null-safety PR?

**Comment by pedroculque** [comment]
Guys, did we have any news about this?

**Comment by rsilvr** [comment]
It's released now: https://pub.dev/packages/easy_mask/versions/2.0.0
