### ISSUE TITLE
getMaskedString não está funcionando

### ISSUE THREAD

**Issue by zeucxb** [danilocoppi/flutter-textfield-mask#4]
Vou escrever em português mesmo, já que vi que são brasileiros.

To tentando usar o `magickMask` (que apropósito acho que seria magic, sem o k, não? O `getAdvancedMaskedStrign` ta escrito errado tb rs Strign ao invés de String).

Já tentei de tudo, mas não funciona.

```dart
final magicMask = TextInputMask(
    mask: '9+.999.999,99',
    placeholder: '0',
    maxPlaceHolders: 3,
    reverse: true,
    maxLength: 14,
 ).magickMask();

magicMask.getMaskedString('10500'); // Retorna os mesmos 10500 sem formatação

magicMask.getAdvancedMaskedStrign('10500' 14, '0', 3) // Erro

MagicMask.buildMask('9+.999.999,99').getMaskedString('10500') // Retorna os mesmos 10500 sem formatação
```

Não sei mais oq tentar rs, queria usar essa lib. O formatter é bem bacana, só o magic que não ta rolando mesmo.

**Comment by danilocoppi** [comment]
Vou dar uma olhada hoje nisso.
Na verdade estamos usando ela e tem outros Bugs que precisa ser revisto.
Ai ja vou aproveitar para corrigir isso tb

**Comment by zeucxb** [comment]
Boa @danilocoppi tentei te adicionar no linkedin e no twitter para trocar uma idéia, mas acho que ainda não viu. Eu fiz uma correção no cleanPlaceholders tb. Posso mandar PR com essa correção e as de nomenclatura.

**Comment by zeucxb** [comment]
Abri o PR #5 😉
