### ISSUE TITLE
Issue ao digitar mais que o tamanho total da mascara

### ISSUE THREAD

**Issue by devfelipereis** [danilocoppi/flutter-textfield-mask#6]
Por exemplo... se eu tenho uma mascara de cpf, ficará assim: 222.222.222-22
São 11 números 2. Se eu apertei mais umas 5 vezes, serão 16. A mascara fica ok mas ao apagar, nada muda.
Teria que apertar o apagar as 5 vezes até chegar ao último caractere da mascara e ai sim começar a apagar.

**Comment by danilocoppi** [comment]
Ja corrigido
